import Header from '@/components/Header';
import Footer from '@/components/Footer';


const page = () => {
  return (
    <>
    <Header/>
     <div className='mt-[5vh] mb-[10vh]' >
      <h2 className='text-center font-extrabold text-4xl'> Privacy & Policy </h2> 

      <div className='px-[5vh] pt-2 lg:px-[35vh] text-[16px]'> 
       <h2 className='text-[18px] pt-9'> Effective date: 10th/04/2026</h2> 

       <div>
        <h2 className='mt-9 text-[20px] font-semibold'>1. <span className='underline'> Introduction </span></h2>
         <h2 className='pt-3'> Welcome to shopnow </h2> 
         <p className='pt-3'> shopnow <span className='font-bold'> (“us”, “we”, or “our”) (hereinafter referred to as “Service ”)</span> .</p>
         <p className='pt-3'>Our Privacy Policy governs your visit to, and explains how we collect, safeguard and disclose information that results from your use of our Service.</p>
         <p className='pt-3'>We use your data to provide and improve Service. By using Service, you agree to the collection and use of information in accordance with this policy. Unless otherwise defined in this Privacy Policy, the terms used in this Privacy Policy have the same meanings as in our Terms and Conditions.</p>
         <p className='pt-3'>Our Terms and Conditions <span className='font-bold'>(“ Terms ”)</span> govern all use of our Service and together with the Privacy Policy constitutes your agreement with us<span className='font-bold'>(“ agreement ”)</span>.</p>
      </div>
      
      <div>
        <h2 className='mt-9 text-[20px] font-semibold'>2. <span className='underline'> Definition </span></h2>
         <p className='pt-3'><span className='font-bold'> PERSONAL DATA</span> means data about a living individual who can be identified from those data (or from those and other information either in our possession or likely to come into our possession).</p>
         <p className='pt-3'><span className='font-bold'>USAGE DATA</span> is data collected automatically either generated by the use of Service or from Service infrastructure itself (for example, the duration of a page visit).</p>
         <p className='pt-3'><span className='font-bold'>COOKIES</span> are small files stored on your device (computer or mobile device).</p>
         <p className='pt-3'><span className='font-bold'> DATA CONTROLLER </span> means a natural or legal person who (either alone or jointly or in common with other persons) determines the purposes for which and the manner in which any personal data are, or are to be, processed. For the purpose of this Privacy Policy, we are a Data Controller of your data.</p>
         <p className='pt-3'><span className='font-bold'> DATA PROCESSORS (OR SERVICE PROVIDERS)</span> means any natural or legal person who processes the data on behalf of the Data Controller. We may use the services of various Service Providers in order to process your data more effectively.</p>
         <p className='pt-3'><span className='font-bold'>DATA SUBJECT</span>  is any living individual who is the subject of Personal Data.</p>
         <p className='pt-3'><span className='font-bold'> THE USER </span>is the individual using our Service. The User corresponds to the Data Subject, who is the subject of Personal Data.</p>
         <p className='pt-3'><span className='font-bold'> CHARGEBACK </span>  is a return of money to a payer of some transaction, especially a credit card transaction Most commonly the payer is a consumer. The chargeback reverses a money transfer from the consumer's bank account, line of credit, or credit card.</p>
      </div>

       
      <div>
        <h2 className='mt-9 text-[20px] font-semibold'>3. <span className='underline'> Information Collection and Use </span></h2>
         <p className='pt-3'>We reserve the right to collect different types of information, and you “the user” are obliged to furnish us with the required information for various purposes, in order to help us provide and improve our Service to you.</p>
      </div>

      <div>
        <h2 className='mt-9 text-[20px] font-semibold'>4. <span className='underline'> Types of Data Collected </span> </h2>
        <h2 className='pt-3'> <span className='font-bold'>Personal Data</span></h2>
        <p>While using our Service, we may require you to provide certain personally identifiable information that can be used to contact or identify you (“Personal Data”). Personal information may include, but not limited to:</p>
        <ul className='pt-3'>
          <li>a. Email address</li>
          <li>b. Full name</li>
          <li>c. Phone number</li>
          <li>d. Cookies and Usage Data</li>
        </ul>
        <p className='pt-3'>We may use your Personal Data to contact you with newsletters, marketing or promotional materials and other information that may be of interest to you. You may opt out of receiving any, or all, of these communications from us by following the unsubscribe link or sending us an email.</p>

        <h2 className='font-bold pt-3'>Usage Data</h2>
        <p>We may also collect information that your browser sends whenever you visit our Service or when you access Service by or through a mobile device (“Usage Data”).</p>    
        <p className='pt-3'>This Usage Data may include information such as your computer's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that you visit, the time and date of your visit, the time spent on those pages, unique device identifiers and other diagnostic data. </p>     
      </div>

      <h2 className='font-bold pt-3'> Location Data </h2>
      <p>We may use and store information about your location if you give us permission to do so (“Location Data”). We use this data to provide features of our Service, to improve and customize our Service.</p>
      <p className='pt-3'>You can enable or disable location services when you use our Service at any time by way of your device settings.</p>

      <h2 className='font-bold pt-3'> Tracking Cookies Data </h2>
      <p> We may use and store information about your location if you give us permission to do so (“Location Data”). We use this data to provide features of our Service, to improve and customize our Service. </p>
      <p className='pt-3'> You can enable or disable location services when you use our Service at any time by way of your device settings. </p>
      
      <div>
      <h2 className='mt-9 text-[20px] font-semibold'>5. <span className='underline'>Retention of Data</span> </h2>
       <p className='pt-3'> We will retain your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use your Personal Data to the extent necessary to comply with our legal obligations (for example, if we are required to retain your data to comply with applicable laws), resolve disputes, and enforce our legal agreements and policies.</p>
       <p className='pt-3'> We will also retain Usage Data for internal analysis purposes. Usage Data is generally retained for a shorter period, except when this data is used to strengthen the security or to improve the functionality of our Service, or we are legally obligated to retain this data for longer time periods. </p> 
      </div>

      <div>
        <h2 className='mt-9 text-[20px] font-semibold'>6.  <span className='underline'> Transfer of Data </span> </h2>
        <p className='pt-3'>Your information, including Personal Data, may be transferred to - and maintained on - computers located outside of your state, province, country or other governmental jurisdiction where the data protection laws may differ from those of your jurisdiction.</p>
        <p className='pt-3'> If you are located outside the United States and choose to provide information to us, please note that we transfer the data, including Personal Data, to the United States and process it there.</p>
        <p className='pt-3'> Your consent to this Privacy Policy followed by your submission of such information represents your agreement to that transfer.</p>
        <p className='pt-3'> Shopnow, inc will take all the steps reasonably necessary to ensure that your data is treated securely and in accordance with this Privacy Policy and no transfer of your Personal Data will take place to an organisation or a country unless there are adequate controls in place including the security of your data and other personal information.</p>
      </div>

      <div> 
        <h2 className='mt-9 text-[20px] font-semibold'> 7. <span className='underline'>Service Providers</span></h2>
        <p className='pt-3'> We may employ third party companies and individuals to facilitate our Service <span className='font-bold'>(“Service Providers ”)</span>, provide Service on our behalf, perform Service-related services or assist us in analysing how our Service is used.</p>
        <p className='pt-3'>These third parties have access to your Personal Data only to perform these tasks on our behalf and are obligated not to disclose or use it for any other purpose.</p>
      </div>

      <div>
        <h2 className='mt-9 text-[20px] font-semibold'>8. <span className='underline'> Analytics </span></h2>
        <p className='pt-3'> We may use third-party Service Providers to monitor and analyze the use of our Service. </p>

        <h2 className='pt-3 font-bold'>Google Analytics</h2>
        <p>Google Analytics is a web analytics service offered by Google that tracks and reports website traffic. Google uses the data collected to track and monitor the use of our Service. This data is shared with other Google services. Google may use the collected data to contextualise and personalise the ads of its own advertising network.</p>
      </div>

      <div>
        <h2 className='mt-9 text-[20px] font-semibold'>9. <span className='underline'> CI/CD tools </span></h2>
        <p className='pt-3'>We may use third-party Service Providers to automate the development process of our Service.</p>
        <h2 className='font-bold pt-3'>GitHub </h2>
        <p className='pt-3'>GitHub is provided by GitHub, Inc.</p>
        <p className='pt-3'> For more information on what data GitHub collects for what purpose and how the protection of the data is ensured, please visit GitHub Privacy Policy page: <a href='https://help.github.com/en/articles/github-privacy-statement' rel="noopener noreferrer" target='_blank' className='text-[blue] hover:text-[blue]'> https://help.github.com/en/articles/github-privacy-statement/</a></p>
      </div>

      <div>
        <h2 className='mt-9 text-[20px] font-semibold'>10. <span className='underline'> Advertising </span></h2>
        <p className='pt-3'>We may use third-party Service Providers to show advertisements to you to help support and maintain our Service.</p>
        <h2 className='font-bold pt-3'>Google AdSense DoubleClick Cookie</h2>
        <p>GitHub is provided by GitHub, Inc.</p>
        <p className='pt-3'>GitHub is a development platform to host and review code, manage projects, and build software. Google, as a third party vendor, uses cookies to serve ads on our Service. Google's use of the DoubleClick cookie enables it and its partners to serve ads to our users based on their visit to our Service or other websites on the Internet.</p>
        <p>You may opt out of the use of the DoubleClick Cookie for interest-based advertising by visiting the Google Ads Settings web page: <a href='http://www.google.com/ads/preferences/' target='_blank'  rel="noopener noreferrer" >http://www.google.com/ads/preferences/</a></p>
      </div>

      <div>
        <h2 className='mt-9 text-[20px] font-semibold'>11. <span className='underline'>Links to Other Sites</span></h2>
        <p className='pt-3'>Our Service may contain links to other sites that are not operated by us. If you click a third party link, you will be directed to that third party's site. We strongly advise you to review the Privacy Policy of every site you visit.</p>
        <p className='pt-3'> We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services. </p>
      </div>

      <div>
        <h2 className='mt-9 text-[20px] font-semibold'>12. <span className='underline'> Changes to This Privacy Policy </span></h2>
        <p className='pt-3'>We may update our Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy on this page.</p>
        <p className='pt-3'> We shall inform you via email and/or a prominent notice on our Service, prior to the change becoming effective and update “effective date” at the top of this Privacy Policy.</p>
        <p className='pt-3'>You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.</p>
      </div>

      <div>
        <h2 className='mt-9 text-[20px] font-semibold'>13. <span className='underline'>Contact Us</span></h2>
        <p>If you have any questions about this Privacy Policy, please contact us:</p>
        <p>By email: <a href='mailto:brightjonathaninfor64@gmail.com'>support@shopnow.com</a></p>
      </div>

      </div> 
    </div>

    <Footer/>
    </>
  )
}

export default page
